version: '3.8'
services: 
  postgres:
    image: postgres
    container_name: mi-postgres2
    environment:
      POSTGRES_USER: alejo
      POSTGRES_PASSWORD: alejo12345
      POSTGRES_DB: carrito
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes: 
  postgres_data: 

networks:
  postgres_network:

